version: '2'
services:
    app:
        build:
            context: ./app/src/
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        volumes:
            - ./app/src/:/home/app/chatbot
        tty: true
        restart: always
